Web/EventsSystem.Web/Controllers/CreateEventController.cs
namespace EventsSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;

    using EventsSystem.Data;
    using EventsSystem.Data.Models;
    using EventsSystem.Services.Data;
    using EventsSystem.Web.InputModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CreateEventController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public CreateEventController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.Db = db;
            this.userManager = userManager;
        }

        public ApplicationDbContext Db { get; }

        [Authorize]
        public IActionResult FillForm()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> FillForm(CreateEventInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var ev = new Event
            {
                Name = input.Name,
                Time = input.Time,
                EntranceFee = input.EntranceFee,
                EntranceType = input.EntranceType,
                Description = input.Description,
                PlaceUrl = "p/" + input.Name.Replace(' ', '-'),
                Initiator = user,
            };

            if (this.Db.Places.Any(p => p.Name.Equals(input.PlaceName) && p.City.Equals(input.PlaceCity) && p.Address.Equals(input.PlaceCity)))
            {
                ev.Place = this.Db.Places.FirstOrDefault(p => p.Name.Equals(input.PlaceName));
            }
            else
            {
                ev.Place = new Place
                {
                    Address = input.PlaceCity,
                    Name = input.PlaceName,
                    City = input.PlaceCity,
                };
            }

            var expectedFileExt = new[] { ".jpg", ".jpeg" };
            if (input.Photos != null)
            {
                foreach (var photo in input.Photos)
                {
                    if (expectedFileExt.Any(x => photo.FileName.EndsWith(x)))
                    {
                        var fileFolder = $"wwwroot\\images\\{input.PlaceName}";
                        System.IO.Directory.CreateDirectory(fileFolder);
                        var path = $"{fileFolder}\\{photo.FileName}";
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await photo.CopyToAsync(fileStream);
                        }

                        ev.Place.Images.Add(new Image
                        {
                            Path = $"images\\{input.PlaceName}\\{photo.FileName}",
                        });
                    }
                }
            }
            else
            {
                if (ev.Place.Images.Count() == 0)
                {
                    ev.Place.Images.Add(new Image
                    {
                        Path = $"images\\defaultPlaceImage.png",
                    });
                }
            }

            this.Db.Events.Add(ev);
            this.Db.SaveChanges();
            return this.Redirect("/");
        }

    }
}

Web/EventsSystem.Web/Controllers/PeopleController.cs
namespace EventsSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using EventsSystem.Data;
    using EventsSystem.Data.Models;
    using EventsSystem.Services.Data;
    using EventsSystem.Web.ViewModels;
    using EventsSystem.Web.ViewModels.AllFreinds;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class PeopleController: Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext db;

        public PeopleController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            this.userManager = userManager;
            this.db = db;
        }

        public async Task<IActionResult> AllFriends()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var friendships = this.db.Friendships.Where(u => u.FriendFrom.Email.Equals(user.Email))
                                                 .Select(e => new Friendship
                                                {
                                                  FriendFrom = e.FriendFrom,
                                                  FriendTo = e.FriendTo,
                                                }).ToList();

            var viewModel = new FriendShipViewModel();
            viewModel.FriendshipsModel = friendships;
            return this.View(viewModel);
        }
    }
}

Web/EventsSystem.Web/Controllers/PlacesController.cs
namespace EventsSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using EventsSystem.Data.Models;
    using EventsSystem.Services.Data;
    using EventsSystem.Web.ViewModels.Events;
    using EventsSystem.Web.ViewModels.Places;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class PlacesController : Controller
    {
        private readonly IPlacesService placesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEventsService eventsService;
        private const int ItemsPerPage = 5;

        public PlacesController(
            IPlacesService placesService,
            UserManager<ApplicationUser> userManager,
            IEventsService eventsService)
        {
            this.placesService = placesService;
            this.userManager = userManager;
            this.eventsService = eventsService;
        }

        public IActionResult ByName(string name)
        {
            var viewModel = this.placesService.GetByName<PlaceViewModel>(name);
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var placeViewModel = this.placesService.GetById<PlaceViewModel>(id);
            if (placeViewModel == null)
            {
                this.RedirectToAction("Error", "Shared");
            }

            var placeWithEventViewModel = new PlaceWithEventViewModel();
            placeWithEventViewModel.Place = placeViewModel;
            placeWithEventViewModel.Events = this.eventsService.GetAllByPlaceId<EventViewModel>(id);

            return this.View(placeWithEventViewModel);
        }

        public async Task<IActionResult> TopPlaces()
        {
            bool isAuthenticated = this.User.Identity.IsAuthenticated;
            var viewModel = new PlaceAllViewModel();
            if (isAuthenticated)
            {
                var user = await this.userManager.GetUserAsync(this.User);
                string city = user.City;
                var places = this.placesService.GetAllByCity<PlaceViewModel>(city, 5, 0);
                viewModel.PlacesByCity = places;
            }

            var allPlaces = this.placesService.GetAll<PlaceViewModel>(5, 0);

            viewModel.AllPlaces = allPlaces;
            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ShowAllPlacesByCity(int page)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            string city = user.City;
            var count = this.placesService.GetCountAllPlacesByCity(city);

            var viewModel = new PlaceAllViewModel();
            var places = this.placesService.GetAllByCity<PlaceViewModel>(city,ItemsPerPage, (page - 1) * ItemsPerPage);

            if (places.Count() == 0)
            {
                return this.RedirectToAction("NoElements", "Shared");
            }

            foreach (var place in places)
            {
                place.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

                place.CurrentPage = page;
            }

            viewModel.PlacesByCity = places;

            return this.View(viewModel);
        }

        public IActionResult ShowAllPlaces(int page)
        {
            var count = this.placesService.GetCount();

            var viewModel = new PlaceAllViewModel();
            var places = this.placesService.GetAll<PlaceViewModel>(ItemsPerPage, (page - 1) * ItemsPerPage);

            if (places.Count() == 0)
            {
                return this.RedirectToAction("NoElements", "Shared");
            }

            foreach (var place in places)
            {
                place.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

                place.CurrentPage = page;
            }

            viewModel.AllPlaces = places;

            return this.View(viewModel);
        }
    }
}

Web/EventsSystem.Web/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventsSystem.Web.Controllers
{
    public class SharedController : Controller
    {
        public IActionResult NoElements()
        {
            return this.View();
        }
    }
}

Web/EventsSystem.Web/Views/Shared/NoElements.cshtml
<section class="page-section portfolio ">
    <div class="container">
        <h1>No Elements</h1>
    </div>
</section>

Web/EventsSystem.Web/Views/Shared/_Layout.cshtml
@using EventsSystem.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/lib/bootstrap-theme/css/styles.css" rel="stylesheet">
    <!-- Fonts CSS-->
    <link rel="stylesheet" href="~/lib/bootstrap-theme/css/heading.css">
    <link rel="stylesheet" href="~/lib/bootstrap-theme/css/body.css">
</head>
<body id="page-top">
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
            <button class="navbar-toggler navbar-toggler-right font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="CreateEvent" asp-action="FillForm">Create event</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Places" asp-action="TopPlaces">Places</a>
                    </li>

                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="People" asp-action="AllFriends">People</a>
                    </li>

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @*<header class="masthead bg-primary text-white text-center">

        </header>*@



    <partial name="_CookieConsentPartial" />
    <main role="main" class="pb-3">
        @this.RenderBody()
    </main>




    <footer class="footer text-center ">
        <div class="container">
            <div class="row">
                <!-- Footer Location-->
                <div class="col-lg-4 mb-5 mb-lg-0">

                </div>
                <!-- Footer Social Icons-->
                <div class="col-lg-4">
                    <h4 class="mb-4"> &copy; @DateTime.Now.Year - @GlobalConstants.SystemName -  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> </h4>

                </div>
                <!-- Footer About Text-->
                <div class="col-lg-4">

                </div>
            </div>
        </div>
    </footer>

    <!-- Copyright Section-->
    <!--<section class="copyright py-4 text-center text-white">
        <div class="container"><small class="pre-wrap">Copyright © Your Website 2020</small></div>
    </section>-->
    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
    <div class="scroll-to-top d-lg-none position-fixed"><a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a></div>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @this.RenderSection("Scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Contact form JS-->
    <script src="~/lib/bootstrap-theme/assets/mail/jqBootstrapValidation.js"></script>
    <script src="~/lib/bootstrap-theme/assets/mail/contact_me.js"></script>
    <!-- Core theme JS-->
    <script src="~/lib/bootstrap-theme/js/scripts.js"></script>

</body>
</html>

Web/EventsSystem.Web/Views/Shared/_NotLoggedLayout.cshtml
@using EventsSystem.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/lib/bootstrap-theme/css/styles.css" rel="stylesheet">
    <!-- Fonts CSS-->
    <link rel="stylesheet" href="~/lib/bootstrap-theme/css/heading.css">
    <link rel="stylesheet" href="~/lib/bootstrap-theme/css/body.css">
</head>
<body id="page-top">
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
            <button class="navbar-toggler navbar-toggler-right font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="CreateEvent" asp-action="FillForm">Create event</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Places" asp-action="TopPlaces">Places</a>
                    </li>

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @*<header class="masthead bg-primary text-white text-center">
        
    </header>*@

   
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @this.RenderBody()
            </main>
   


    <footer class="footer text-center ">
        <div class="container">
            <div class="row">
                <!-- Footer Location-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                   
                </div>
                <!-- Footer Social Icons-->
                <div class="col-lg-4">
                    <h4 class="mb-4"> &copy; @DateTime.Now.Year - @GlobalConstants.SystemName -  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> </h4>
                    
                </div>
                <!-- Footer About Text-->
                <div class="col-lg-4">
                    
                </div>
            </div>
        </div>
    </footer>

      <!-- Copyright Section-->
        <!--<section class="copyright py-4 text-center text-white">
            <div class="container"><small class="pre-wrap">Copyright © Your Website 2020</small></div>
        </section>-->

   

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
    <div class="scroll-to-top d-lg-none position-fixed"><a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a></div>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @this.RenderSection("Scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Contact form JS-->
    <script src="~/lib/bootstrap-theme/assets/mail/jqBootstrapValidation.js"></script>
    <script src="~/lib/bootstrap-theme/assets/mail/contact_me.js"></script>
    <!-- Core theme JS-->
    <script src="~/lib/bootstrap-theme/js/scripts.js"></script>

</body>
</html>