Web/EventsSystem.Web/Controllers/EventsController.cs
namespace EventsSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using EventsSystem.Data.Models;
    using EventsSystem.Services.Data;
    using EventsSystem.Web.ViewModels.Events;
    using EventsSystem.Web.ViewModels.Home;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class EventsController : Controller
    {
        private readonly IEventsService eventsService;
        private readonly UserManager<ApplicationUser> userManager;
        private const int ItemsPerPage = 5;

        public EventsController(IEventsService eventsService, UserManager<ApplicationUser> userManager)
        {
            this.eventsService = eventsService;
            this.userManager = userManager;
        }

        public IActionResult EventsByName(string name)
        {
            var viewModel = this.eventsService.GetByName<EventViewModel>(name);
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var postViewModel = this.eventsService.GetById<EventViewModel>(id);
            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }

        public IActionResult ShowAllEvents(int page)
        {
            var count = this.eventsService.GetCountAllUpcomingEvents();

            var viewModel = new ViewModels.Home.IndexViewModel();
            var events = this.eventsService.GetAll<IndexEventViewModel>(ItemsPerPage, (page - 1) * ItemsPerPage);
            if (events.Count() == 0)
            {
                return this.RedirectToAction("NoElements", "Shared");
            }

            foreach (var ev in events)
            {
                ev.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

                ev.CurrentPage = page;
            }

            viewModel.Events = events;

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ShowAllEventsByCity(int page)
        {
            var viewModel = new ViewModels.Home.IndexViewModel();
            var user = await this.userManager.GetUserAsync(this.User);
            string city = user.City;
            var count = this.eventsService.GetCountAllUpcomingEventsByCity(city);

            var eventsByCity = this.eventsService.GetAllByCity<IndexEventViewModel>(city, ItemsPerPage, (page - 1) * ItemsPerPage);
            if (eventsByCity.Count() == 0)
            {
                return this.RedirectToAction("NoElements", "Shared");
            }

            viewModel.EventsByCity = eventsByCity;
            foreach (var ev in eventsByCity)
            {
                ev.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

                ev.CurrentPage = page;
            }

            viewModel.EventsByCity = eventsByCity;

            return this.View(viewModel);
        }
    }
}

Web/EventsSystem.Web/Controllers/PlacesController.cs
namespace EventsSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using EventsSystem.Data.Models;
    using EventsSystem.Services.Data;
    using EventsSystem.Web.ViewModels.Events;
    using EventsSystem.Web.ViewModels.Places;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class PlacesController : Controller
    {
        private readonly IPlacesService placesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEventsService eventsService;
        private const int ItemsPerPage = 5;

        public PlacesController(
            IPlacesService placesService,
            UserManager<ApplicationUser> userManager,
            IEventsService eventsService)
        {
            this.placesService = placesService;
            this.userManager = userManager;
            this.eventsService = eventsService;
        }

        public IActionResult ByName(string name)
        {
            var viewModel = this.placesService.GetByName<PlaceViewModel>(name);
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var placeViewModel = this.placesService.GetById<PlaceViewModel>(id);
            if (placeViewModel == null)
            {
                this.RedirectToAction("Error", "Shared");
            }

            var placeWithEventViewModel = new PlaceWithEventViewModel();
            placeWithEventViewModel.Place = placeViewModel;
            placeWithEventViewModel.Events = this.eventsService.GetAllByPlaceId<EventViewModel>(id);

            return this.View(placeWithEventViewModel);
        }

        public async Task<IActionResult> TopPlaces()
        {
            bool isAuthenticated = this.User.Identity.IsAuthenticated;
            var viewModel = new PlaceAllViewModel();
            if (isAuthenticated)
            {
                var user = await this.userManager.GetUserAsync(this.User);
                string city = user.City;
                var places = this.placesService.GetAllByCity<PlaceViewModel>(city, 5, 0);
                viewModel.PlacesByCity = places;
            }

            var allPlaces = this.placesService.GetAll<PlaceViewModel>(5, 0);

            viewModel.AllPlaces = allPlaces;
            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ShowAllPlacesByCity(int page)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            string city = user.City;
            var count = this.placesService.GetCountAllPlacesByCity(city);

            var viewModel = new PlaceAllViewModel();
            var places = this.placesService.GetAllByCity<PlaceViewModel>(city,ItemsPerPage, (page - 1) * ItemsPerPage);

            if (places.Count() == 0)
            {
                return this.RedirectToAction("NoElements", "Shared");
            }

            foreach (var place in places)
            {
                place.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

                place.CurrentPage = page;
            }

            viewModel.PlacesByCity = places;

            return this.View(viewModel);
        }

        public IActionResult ShowAllPlaces(int page)
        {
            var count = this.placesService.GetCount();

            var viewModel = new PlaceAllViewModel();
            var places = this.placesService.GetAll<PlaceViewModel>(ItemsPerPage, (page - 1) * ItemsPerPage);

            if (places.Count() == 0)
            {
                return this.RedirectToAction("NoElements", "Shared");
            }

            foreach (var place in places)
            {
                place.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

                place.CurrentPage = page;
            }

            viewModel.AllPlaces = places;

            return this.View(viewModel);
        }
    }
}

Web/EventsSystem.Web/Views/Events/ById.cshtml
@using EventsSystem.Common
@model EventsSystem.Web.ViewModels.Events.EventViewModel

<section class="page-section portfolio ">
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Post Content Column -->
            <div class="col-lg-8">

                <!-- Title -->
                <h1 class="mt-4">@Model.Name</h1>

                <!-- Author -->
                <p class="lead">
                    Location:
                    <a asp-controller="Places" asp-action="ById" asp-route-id="@Model.PlaceId">@Model.Place.Name</a>
                </p>
                <div class="text-muted small ml-3">
                    <form id="votesForm" method="post"></form>
                    <div>
                        <a href="#" onclick="sendVote(@Model.Id, true)">
                            <i class="fa fa-thumbs-up"></i>
                        </a>
                    </div>
                    <div id="votesCount">@Model.VotesCount interested</div>
                    <div>
                        <a href="#" onclick="sendVote(@Model.Id, false)">
                            <i class="fa fa-thumbs-down"></i>
                        </a>
                    </div>
                </div>

                <hr>

                <!-- Date/Time -->
                <p>Time @Model.Time</p>

                <hr>

                <!-- Post Content -->
                <p class="lead">@Html.Raw(Model.SanitizedDescription)</p>



                <hr>



            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

        <!-- Carousel -->
        
        <div class="row ">
            <div id="carouselExampleControls" class="carousel slide col-md-6" data-ride="carousel">
                <h3>Pictures from the location</h3>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="@Url.Content($"~/{Model.PlaceImages.First().Path}")" class="d-block w-100" alt="...">
                    </div>
                    @foreach (var item in Model.PlaceImages.Skip(1))
                    {
                        <div class="carousel-item">
                            <img src="@Url.Content($"~/{item.Path}")" class="d-block w-100" alt="...">
                        </div>
                    }
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>

            </div>
        </div>
        <!-- /.Carousel -->

</section>

<section class="page-section" id="contact">
</section>

    @section Scripts {
        <script>
            function sendVote(eventId, isUpVote) {
                var token = $("#votesForm input[name=__RequestVerificationToken]").val();
                var json = { eventId: eventId, isUpVote: isUpVote };
                $.ajax({
                    url: "/api/votesevent",
                    type: "POST",
                    data: JSON.stringify(json),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    headers: { 'X-CSRF-TOKEN': token },
                    success: function (data) {
                        $("#votesCount").html(data.votesCount + " interested");
                        console.log(data.votesCount)
                    }
                });
            }
        </script>
    }

Web/EventsSystem.Web/Views/Events/EventsByName.cshtml
@using EventsSystem.Common
@model EventsSystem.Web.ViewModels.Events.EventViewModel

<div class="media">
    <div class="media-body">
        <h1 class="text-center mt-0 mb-1 text-justify">
            @Model.Name
            <small class="text-muted">@Model.Place.Address</small>
        </h1>
    </div>

</div>

<div class="media">
    <div class="media-body">
        <h5 class="mt-0">Description</h5>
        <p>@Html.Raw(Model.SanitizedDescription)</p>
    </div>
</div>

<div class="media">
    <div class="media-body">
        <h5 class="mt-0">Time of The Event</h5>
        <p>@Model.Time</p>
    </div>
</div>

<div class="media">
    <div class="media-body">
        <h5 class="mt-0">Place of event</h5>
        <p>@Model.Place.Address</p>
    </div>

    <div class="media-body">
        <h4 class="media-heading">
        <a asp-controller="Places" asp-action="ById" asp-route-id="@Model.PlaceId">@Model.Place.Name</a>
        </h4>

    </div>
</div>

@if (Model.EntranceFee != 0)
{
    <div class="media">
        <div class="media-body">
            <h5 class="mt-0">Entrance</h5>
            <p>@Model.EntranceFee lv</p>
        </div>
    </div>
}

else
{
    <div class="media">
        <div class="media-body">
            <h5 class="mt-0">Entrance</h5>
            <p>Free</p>
        </div>
    </div>

}

Web/EventsSystem.Web/Views/Events/ShowAllEvents.cshtml
@using EventsSystem.Common
@model EventsSystem.Web.ViewModels.Home.IndexViewModel
    <section class="page-section portfolio ">
        <div class="container">
            <h3 class="display-4 mt-3 ">All upcomming events</h3>
                @foreach (var ev in Model.Events)
                {
            <div class="list-group ">
                <a asp-controller="Events" asp-action="ById" asp-route-id="@ev.Id" class=" col-md-5 mt-5 mb-2 list-group-item list-group-item-action flex-column align-items-start active">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">@ev.Name</h5>
                        <small>@ev.Time</small>
                    </div>
                    <small>@ev.Place.City</small>
                </a>
            </div>
            }
            
            </div>

            <nav class="mt-3">
                <ul class="pagination justify-content-center">
                    @if (this.Model.Events.ElementAt(0).CurrentPage == 1)
                    {
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
 }
    else
    {
        <li class="page-item">
            <a class="page-link"
               asp-route="allEvents"
               asp-route-page="@(this.Model.Events.ElementAt(0).CurrentPage - 1)">Previous</a>
        </li>
}

                    @for (int i = 1; i <= this.Model.Events.ElementAt(0).PagesCount; i++)
                    {
                        var active = i == this.Model.Events.ElementAt(0).CurrentPage ? "active" : string.Empty;
        <li class="page-item @active">
            <a class="page-link"
               asp-route="allEvents"
               asp-route-page="@i">@i</a>
        </li>
}

                    @if (this.Model.Events.ElementAt(0).CurrentPage == this.Model.Events.ElementAt(0).PagesCount)
                    {
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
 }
    else
    {
        <li class="page-item">
            <a class="page-link"
               asp-route="allEvents"
               asp-route-page="@(this.Model.Events.ElementAt(0).CurrentPage + 1)">Next</a>
        </li>
}
                </ul>
            </nav>

</section>

    <section class="page-section" id="contact">
    </section>

Web/EventsSystem.Web/Views/Events/ShowAllEventsByCity.cshtml
@using EventsSystem.Common
@model EventsSystem.Web.ViewModels.Home.IndexViewModel
    <section class="page-section portfolio ">
        <div class="container">
            @foreach (var ev in Model.EventsByCity)
            {

            <div class="list-group ">
                <a asp-controller="Events" asp-action="ById" asp-route-id="@ev.Id" class=" col-md-5 mt-5 mb-2 list-group-item list-group-item-action flex-column align-items-start active">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">@ev.Name</h5>
                        <small>@ev.Time</small>
                    </div>
                    <small>@ev.Place.City</small>
                </a>
            </div>   
        
        }
        </div>

        <nav>
            <ul class="pagination justify-content-center">

                @if (this.Model.EventsByCity.ElementAt(0).CurrentPage == 1)
                {
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Previous</a>
                    </li> }

                else
                {
                     <li class="page-item">
                         <a class="page-link"
                            asp-route="allEventsByCity"
                            asp-route-page="@(this.Model.EventsByCity.ElementAt(0).CurrentPage - 1)">Previous</a>
                     </li>}


                @for (int i = 1; i <= this.Model.EventsByCity.ElementAt(0).PagesCount; i++)
                {
                    var active = i == this.Model.EventsByCity.ElementAt(0).CurrentPage ? "active" : string.Empty;
                    <li class="page-item @active">
                        <a class="page-link"
                           asp-route="allEventsByCity"
                           asp-route-page="@i">@i</a>
                    </li>}

                @if (this.Model.EventsByCity.ElementAt(0).CurrentPage == this.Model.EventsByCity.ElementAt(0).PagesCount)
                {
                     <li class="page-item disabled">
                         <a class="page-link" href="#">Next</a>
                     </li> }
                else
                {
                     <li class="page-item">
                         <a class="page-link"
                            asp-route="allEventsByCity"
                            asp-route-page="@(this.Model.EventsByCity.ElementAt(0).CurrentPage + 1)">Next</a>
                     </li>}

            </ul>
        </nav>
    </section>

    <section class="page-section" id="contact">
    </section>